#!/bin/bash
echo "" #gap between log entries
date -u #prints the date out for the log

#run python script to download updates and update the database
python /home/pha17gh/TNS/tns_update.py

#move all updates to old updates directory
mv /home/pha17gh/TNS/tns_public_objects_* /home/pha17gh/TNS/old_updates/

#copy old pscores csv to directory
cp /home/pha17gh/TNS/transient_list-F.csv /home/pha17gh/TNS/old_pscores/transient_list_${yesterday}-F.csv
cp /home/pha17gh/TNS/transient_list-S.csv /home/pha17gh/TNS/old_pscores/transient_list_${yesterday}-S.csv

#run filtering and pscore calculator
python /home/pha17gh/TNS/fastslow.py

#send automated email with priority scores attached
cd /home/pha17gh/TNS/mail/ #need to move to directory so it can find the json files to send the email
python /home/pha17gh/TNS/mail/email_alert.py
